version: '3.3'

x-db_credentials: &db-credentials
  MONGO_INITDB_ROOT_USERNAME: weather_api_admin
  MONGO_INITDB_ROOT_PASSWORD: weather_api_pass

services:
  weather-app:
    build:
      context: ./weather
      dockerfile: weather.yml
    image: weather-app
    networks:
      - api
    ports:
      - 6000:5000
    depends_on:
      - db
    restart: always
    environment:
      <<: *db-credentials
      MONGO_HOST: db
      MONGO_PORT: 27017
      DB_NAME: weather_data

  db:
    image: mongo:latest
    container_name: mongo-server
    networks:
      - api
      - tools
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    restart: always
    environment: *db-credentials

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    networks:
      - tools
    ports:
      - 8111:8081
    depends_on:
      - db
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: weather_api_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: weather_api_pass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

volumes:
  db_data: {}

networks:
  api:
    name: weather_api_network
  tools:
    name: external_tools_network